import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {Divider} from 'antd';
import logos from '../public/images/defaultlogo.png';
import Index from "../components/InputComponent";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Personal Task manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <header>
        <Image src={logos} width={80} height={80}/>
      </header>
      <Divider/>
      <Index/>
    </div>
  )
}
